version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: database-postgre
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 2nl3kju4h8f
      POSTGRES_DB: sanbercode
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: eps_app
  #   restart: always
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=eps_user
  #     - DB_PASSWORD=eps_secret
  #     - DB_NAME=eps_db
  #     - JWT_SECRET=SuperSecretKey123
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"

volumes:
  db_data:
